services:
  - type: web
    name: stress-backend
    env: python
    rootDir: src
    buildCommand: "pip install -r src/requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 8000"
    plan: free
